<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AiGenerationFeedbackSeeder extends Seeder
{
    /**
     * Auto-generated from database table `ai_generation_feedback`.
     * Total records: 39
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('ai_generation_feedback')->delete();

        $rows = [
            [
                'id' => '4',
                'session_id' => 'sess_nf4n1mi_1789167353441',
                'message_id' => '1789167511545',
                'tool_log_id' => '109',
                'tool_name' => 'listar_proveedores',
                'pedido_id' => null,
                'tipo_operacion' => 'listar_proveedores',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 17:58:45.467',
                'updated_at' => '2026-09-11 17:58:45.467',
            ],
            [
                'id' => '5',
                'session_id' => 'sess_k8ir0xn_1789167956042',
                'message_id' => '1789168027091',
                'tool_log_id' => '118',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:07:12.687',
                'updated_at' => '2026-09-11 18:07:12.687',
            ],
            [
                'id' => '6',
                'session_id' => 'sess_k8ir0xn_1789167956042',
                'message_id' => '1789168246628',
                'tool_log_id' => '124',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:11:13.337',
                'updated_at' => '2026-09-11 18:11:13.337',
            ],
            [
                'id' => '7',
                'session_id' => 'sess_k8ir0xn_1789167956042',
                'message_id' => '1789168288467',
                'tool_log_id' => '125',
                'tool_name' => 'listar_proveedores',
                'pedido_id' => null,
                'tipo_operacion' => 'listar_proveedores',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:17:28.180',
                'updated_at' => '2026-09-11 18:17:28.180',
            ],
            [
                'id' => '8',
                'session_id' => 'sess_k8ir0xn_1789167956042',
                'message_id' => '1789168309448',
                'tool_log_id' => '126',
                'tool_name' => 'abrir_formulario_orden_compra',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_orden_compra',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:17:29.993',
                'updated_at' => '2026-09-11 18:17:29.993',
            ],
            [
                'id' => '9',
                'session_id' => 'sess_l4csvms_1789168790542',
                'message_id' => '1789169341091',
                'tool_log_id' => '138',
                'tool_name' => 'buscar_cliente',
                'pedido_id' => null,
                'tipo_operacion' => 'buscar_cliente',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:29:17.913',
                'updated_at' => '2026-09-11 18:29:17.913',
            ],
            [
                'id' => '10',
                'session_id' => 'sess_l4csvms_1789168790542',
                'message_id' => '1789169286137',
                'tool_log_id' => '136',
                'tool_name' => 'buscar_cliente',
                'pedido_id' => null,
                'tipo_operacion' => 'buscar_cliente',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:29:28.283',
                'updated_at' => '2026-09-11 18:29:28.283',
            ],
            [
                'id' => '11',
                'session_id' => 'sess_l4csvms_1789168790542',
                'message_id' => '1789169377903',
                'tool_log_id' => null,
                'tool_name' => null,
                'pedido_id' => null,
                'tipo_operacion' => 'consulta_operativa',
                'rating' => 'dislike',
                'es_correcto' => '0',
                'motivo_dislike' => 'Error de interpretación',
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:29:47.653',
                'updated_at' => '2026-09-11 18:30:00.173',
            ],
            [
                'id' => '12',
                'session_id' => 'sess_l4csvms_1789168790542',
                'message_id' => '1789169548769',
                'tool_log_id' => null,
                'tool_name' => null,
                'pedido_id' => null,
                'tipo_operacion' => 'consulta_operativa',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:36:32.947',
                'updated_at' => '2026-09-11 18:36:32.947',
            ],
            [
                'id' => '13',
                'session_id' => 'sess_l4csvms_1789168790542',
                'message_id' => '1789169561011',
                'tool_log_id' => null,
                'tool_name' => null,
                'pedido_id' => null,
                'tipo_operacion' => 'consulta_operativa',
                'rating' => 'dislike',
                'es_correcto' => '0',
                'motivo_dislike' => 'Error de interpretación',
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:36:36.530',
                'updated_at' => '2026-09-11 18:36:36.530',
            ],
            [
                'id' => '14',
                'session_id' => 'sess_qmyvq84_1789170637240',
                'message_id' => '1789170753405',
                'tool_log_id' => '147',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:52:55.460',
                'updated_at' => '2026-09-11 18:52:55.460',
            ],
            [
                'id' => '15',
                'session_id' => 'sess_qmyvq84_1789170637240',
                'message_id' => '1789170732415',
                'tool_log_id' => '146',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:52:57.327',
                'updated_at' => '2026-09-11 18:52:57.327',
            ],
            [
                'id' => '16',
                'session_id' => 'sess_qmyvq84_1789170637240',
                'message_id' => '1789170663489',
                'tool_log_id' => '145',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 18:53:00.887',
                'updated_at' => '2026-09-11 18:53:00.887',
            ],
            [
                'id' => '17',
                'session_id' => 'sess_wonzey5_1789171108893',
                'message_id' => '1789171668889',
                'tool_log_id' => '149',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 19:08:02.100',
                'updated_at' => '2026-09-11 19:08:02.100',
            ],
            [
                'id' => '18',
                'session_id' => 'sess_wonzey5_1789171108893',
                'message_id' => '1789171713341',
                'tool_log_id' => '150',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 19:08:56.640',
                'updated_at' => '2026-09-11 19:08:56.640',
            ],
            [
                'id' => '19',
                'session_id' => 'sess_wonzey5_1789171108893',
                'message_id' => '1789171732240',
                'tool_log_id' => '151',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 19:09:07.627',
                'updated_at' => '2026-09-11 19:09:07.627',
            ],
            [
                'id' => '20',
                'session_id' => 'sess_t23us3z_1789171794860',
                'message_id' => '1789171818044',
                'tool_log_id' => '159',
                'tool_name' => 'consultar_kpi',
                'pedido_id' => null,
                'tipo_operacion' => 'consultar_kpi',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 19:10:32.733',
                'updated_at' => '2026-09-11 19:10:32.733',
            ],
            [
                'id' => '21',
                'session_id' => 'sess_t23us3z_1789171794860',
                'message_id' => '1789171811018',
                'tool_log_id' => '154',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-11 19:10:36.220',
                'updated_at' => '2026-09-11 19:10:36.220',
            ],
            [
                'id' => '22',
                'session_id' => 'sess_6mjwbky_1789518985784',
                'message_id' => '1789518998674',
                'tool_log_id' => '10161',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'dislike',
                'es_correcto' => '0',
                'motivo_dislike' => 'Otro motivo',
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 19:36:48.367',
                'updated_at' => '2026-09-15 19:36:48.367',
            ],
            [
                'id' => '23',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789520251267',
                'tool_log_id' => '10164',
                'tool_name' => 'consultar_kpi',
                'pedido_id' => null,
                'tipo_operacion' => 'consultar_kpi',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 19:57:39.773',
                'updated_at' => '2026-09-15 19:57:39.773',
            ],
            [
                'id' => '24',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789520242111',
                'tool_log_id' => '10163',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 19:57:41.683',
                'updated_at' => '2026-09-15 19:57:41.683',
            ],
            [
                'id' => '25',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789521023283',
                'tool_log_id' => '10170',
                'tool_name' => 'listar_productos_bajo_stock',
                'pedido_id' => null,
                'tipo_operacion' => 'listar_productos_bajo_stock',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 20:10:34.913',
                'updated_at' => '2026-09-15 20:10:34.913',
            ],
            [
                'id' => '26',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789521012919',
                'tool_log_id' => '10169',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 20:10:34.943',
                'updated_at' => '2026-09-15 20:10:34.943',
            ],
            [
                'id' => '27',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789521031098',
                'tool_log_id' => '10171',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 20:10:40.367',
                'updated_at' => '2026-09-15 20:10:40.367',
            ],
            [
                'id' => '28',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789521007087',
                'tool_log_id' => '10168',
                'tool_name' => 'generar_reporte_periodo',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_reporte_periodo',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 20:10:44.453',
                'updated_at' => '2026-09-15 20:10:44.453',
            ],
            [
                'id' => '29',
                'session_id' => 'sess_0lywzvz_1789520231678',
                'message_id' => '1789520991524',
                'tool_log_id' => '10167',
                'tool_name' => 'consultar_kpi',
                'pedido_id' => null,
                'tipo_operacion' => 'consultar_kpi',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-15 20:10:48.410',
                'updated_at' => '2026-09-15 20:10:48.410',
            ],
            [
                'id' => '30',
                'session_id' => 'sess_mjjoly5_1789596970314',
                'message_id' => '1789603377451',
                'tool_log_id' => '10178',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:03:23.263',
                'updated_at' => '2026-09-16 19:03:23.263',
            ],
            [
                'id' => '31',
                'session_id' => 'sess_mjjoly5_1789596970314',
                'message_id' => '1789603349057',
                'tool_log_id' => '10177',
                'tool_name' => 'buscar_cliente',
                'pedido_id' => null,
                'tipo_operacion' => 'buscar_cliente',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:03:23.297',
                'updated_at' => '2026-09-16 19:03:23.297',
            ],
            [
                'id' => '32',
                'session_id' => 'sess_mjjoly5_1789596970314',
                'message_id' => '1789603410624',
                'tool_log_id' => null,
                'tool_name' => null,
                'pedido_id' => null,
                'tipo_operacion' => 'consulta_operativa',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:04:27.993',
                'updated_at' => '2026-09-16 19:04:27.993',
            ],
            [
                'id' => '33',
                'session_id' => 'sess_mjjoly5_1789596970314',
                'message_id' => '1789603421523',
                'tool_log_id' => '10180',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:06:31.147',
                'updated_at' => '2026-09-16 19:06:31.147',
            ],
            [
                'id' => '34',
                'session_id' => 'sess_40cgazt_1789603713360',
                'message_id' => '1789603726133',
                'tool_log_id' => '10181',
                'tool_name' => 'listar_graficos_disponibles',
                'pedido_id' => null,
                'tipo_operacion' => 'listar_graficos_disponibles',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:09:10.493',
                'updated_at' => '2026-09-16 19:09:10.493',
            ],
            [
                'id' => '35',
                'session_id' => 'sess_40cgazt_1789603713360',
                'message_id' => '1789603750831',
                'tool_log_id' => '10186',
                'tool_name' => 'consultar_kpi',
                'pedido_id' => null,
                'tipo_operacion' => 'consultar_kpi',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:10:02.160',
                'updated_at' => '2026-09-16 19:10:02.160',
            ],
            [
                'id' => '36',
                'session_id' => 'sess_40cgazt_1789603713360',
                'message_id' => '1789603841684',
                'tool_log_id' => '10189',
                'tool_name' => 'generar_grafico_dashboard',
                'pedido_id' => null,
                'tipo_operacion' => 'generar_grafico_dashboard',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:11:09.503',
                'updated_at' => '2026-09-16 19:11:09.503',
            ],
            [
                'id' => '37',
                'session_id' => 'sess_40cgazt_1789603713360',
                'message_id' => '1789603814489',
                'tool_log_id' => '10188',
                'tool_name' => 'listar_productos_bajo_stock',
                'pedido_id' => null,
                'tipo_operacion' => 'listar_productos_bajo_stock',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-16 19:11:13.493',
                'updated_at' => '2026-09-16 19:11:13.493',
            ],
            [
                'id' => '10022',
                'session_id' => 'sess_8mqxwn9_1789770070114',
                'message_id' => '1789770100230',
                'tool_log_id' => null,
                'tool_name' => null,
                'pedido_id' => null,
                'tipo_operacion' => 'consulta_operativa',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-18 17:21:57.480',
                'updated_at' => '2026-09-18 17:21:57.480',
            ],
            [
                'id' => '10023',
                'session_id' => 'sess_a501l1g_1789770800170',
                'message_id' => '1789770860641',
                'tool_log_id' => '20170',
                'tool_name' => 'abrir_formulario_cliente',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_cliente',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-18 17:34:39.627',
                'updated_at' => '2026-09-18 17:34:39.627',
            ],
            [
                'id' => '10024',
                'session_id' => 'sess_a501l1g_1789770800170',
                'message_id' => '1789770819975',
                'tool_log_id' => '20169',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-18 17:34:41.197',
                'updated_at' => '2026-09-18 17:34:41.197',
            ],
            [
                'id' => '10025',
                'session_id' => 'sess_a501l1g_1789770800170',
                'message_id' => '1789770809840',
                'tool_log_id' => '20168',
                'tool_name' => 'abrir_formulario_pedido',
                'pedido_id' => null,
                'tipo_operacion' => 'abrir_formulario_pedido',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-18 17:34:42.757',
                'updated_at' => '2026-09-18 17:34:42.757',
            ],
            [
                'id' => '20022',
                'session_id' => 'sess_ozczfif_1790218494800',
                'message_id' => '1790218716370',
                'tool_log_id' => '30163',
                'tool_name' => 'obtener_predicciones_compra',
                'pedido_id' => null,
                'tipo_operacion' => 'obtener_predicciones_compra',
                'rating' => 'like',
                'es_correcto' => '1',
                'motivo_dislike' => null,
                'comentario' => null,
                'user_id' => null,
                'created_at' => '2026-09-23 21:58:49.977',
                'updated_at' => '2026-09-23 21:58:49.977',
            ],
        ];

        // Inserción en bloques con IDENTITY_INSERT habilitado
        foreach (array_chunk($rows, 25) as $chunk) {
            if (empty($chunk)) continue;
            $columns = array_keys($chunk[0]);
            $colList = '[' . implode('], [', $columns) . ']';

            $valuesSql = [];
            foreach ($chunk as $r) {
                $valParts = [];
                foreach ($r as $val) {
                    if ($val === null) {
                        $valParts[] = 'NULL';
                    } elseif (is_numeric($val) && !is_string($val)) {
                        $valParts[] = $val;
                    } elseif (is_bool($val)) {
                        $valParts[] = $val ? '1' : '0';
                    } else {
                        $escaped = str_replace("'", "''", (string)$val);
                        $valParts[] = "N'" . $escaped . "'";
                    }
                }
                $valuesSql[] = '(' . implode(', ', $valParts) . ')';
            }

            $sql = "SET IDENTITY_INSERT [ai_generation_feedback] ON;\n"
                 . "INSERT INTO [ai_generation_feedback] ($colList) VALUES\n"
                 . implode(",\n", $valuesSql) . ";\n"
                 . "SET IDENTITY_INSERT [ai_generation_feedback] OFF;";

            DB::unprepared($sql);
        }

        // Reactivar restricciones de claves foráneas
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"');
    }
}
