<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Cliente`.
     * Total records: 17
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Cliente')->delete();

        $rows = [
            [
                'ClienteId' => 'CLI-00001',
                'ClienteNombre' => 'Bodega Los Amigos',
                'ClienteDireccion' => 'Av. Las Flores 123',
                'ClienteNumero' => '+51 987123456',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20601234565',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-07-17 22:53:35.523',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00002',
                'ClienteNombre' => 'Supermercado Central',
                'ClienteDireccion' => 'Jr. Comercio 456',
                'ClienteNumero' => '+51 912345678',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20559876543',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-05-06 22:53:35.523',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00003',
                'ClienteNombre' => 'Restaurante La Plaza',
                'ClienteDireccion' => 'Plaza de Armas 789',
                'ClienteNumero' => '+51 998877665',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20448765432',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-06-07 22:53:35.523',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00004',
                'ClienteNombre' => 'Minimarket El Sol',
                'ClienteDireccion' => 'Calle Las Begonias 321',
                'ClienteNumero' => '+51 955443322',
                'ClienteEstado' => 'I',
                'ClienteRuc' => '10456789019',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-08-09 22:53:35.523',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-05 23:00:36.553',
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00005',
                'ClienteNombre' => 'Bodega Don Pepe',
                'ClienteDireccion' => 'Av. Grau 555',
                'ClienteNumero' => '+51 911223344',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '10765432109',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-08-05 22:53:35.523',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-05 23:23:11.283',
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00006',
                'ClienteNombre' => 'Distribuidora Santa Rosa',
                'ClienteDireccion' => 'Av. Industrial 100',
                'ClienteNumero' => '+51 900112233',
                'ClienteEstado' => 'I',
                'ClienteRuc' => '20112233441',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'SEEDER',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-05-06 22:53:35.523',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-05 22:59:02.530',
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00007',
                'ClienteNombre' => 'Superintendencia Nacional SUNAT Actualizado',
                'ClienteDireccion' => 'Av. Javier Prado Este 456',
                'ClienteNumero' => '+51 988111222',
                'ClienteEstado' => 'I',
                'ClienteRuc' => '20131312955',
                'ClienteEliminado' => 'S',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-05 23:23:11.223',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-05 23:23:11.263',
                'ClienteUsuarioEliminacion' => 'ADMIN',
                'ClienteHostEliminacion' => '127.0.0.1',
                'ClienteFechaEliminacion' => '2026-09-05 23:23:11.270',
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00008',
                'ClienteNombre' => 'MIGUEL BLAS JANETT MARGARITA',
                'ClienteDireccion' => '-',
                'ClienteNumero' => '900292514',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '10417290937',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-07 20:05:41.207',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00009',
                'ClienteNombre' => 'VALENCIA VILLANUEVA BERNABE',
                'ClienteDireccion' => 'MZ 14 LT 12A',
                'ClienteNumero' => '1992136527',
                'ClienteEstado' => 'I',
                'ClienteRuc' => '10181935451',
                'ClienteEliminado' => 'S',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-07 20:40:23.300',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => 'ADMIN',
                'ClienteHostEliminacion' => '127.0.0.1',
                'ClienteFechaEliminacion' => '2026-09-07 22:04:46.383',
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00010',
                'ClienteNombre' => 'SUPERMERCADOS PERUANOS SOCIEDAD ANONIMA \'O \' S.P.S.A.',
                'ClienteDireccion' => 'CAL. MORELLI NRO 181 INT. P-2, SAN BORJA - LIMA - LIMA',
                'ClienteNumero' => '987654321',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20100070970',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-07 20:41:17.187',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-07 20:41:25.540',
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00011',
                'ClienteNombre' => 'CLIENTE GENERAL / VENTA AL POR MENOR',
                'ClienteDireccion' => 'Venta en Tienda / Mostrador',
                'ClienteNumero' => '000000000',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '00000000000',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-09 09:42:12.573',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00012',
                'ClienteNombre' => 'Inversiones Los Andes SAC',
                'ClienteDireccion' => 'Av. Primavera 456',
                'ClienteNumero' => '987111222',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20609999991',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-10 15:09:18.763',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00013',
                'ClienteNombre' => 'Distribuidora Norte SAC',
                'ClienteDireccion' => 'Jr. Trujillo 789',
                'ClienteNumero' => '955443322',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '20601234568',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-10 15:15:54.260',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00014',
                'ClienteNombre' => 'Doña Janeeth',
                'ClienteDireccion' => 'Viru Av.Guerrero 172',
                'ClienteNumero' => '987654654',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '10110000010',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-10 15:18:25.980',
                'ClienteUsuarioModificacion' => 'ADMIN',
                'ClienteHostModificacion' => '127.0.0.1',
                'ClienteFechaModificacion' => '2026-09-26 19:44:05.907',
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00015',
                'ClienteNombre' => 'Don Juan',
                'ClienteDireccion' => 'Trujillo Av. America 123',
                'ClienteNumero' => '987474585',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '101111000',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-10 15:51:36.080',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00016',
                'ClienteNombre' => 'Bodega San Martin',
                'ClienteDireccion' => 'Av. San Martin 789',
                'ClienteNumero' => '987654321',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '10456789012',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-10 16:51:18.760',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
            [
                'ClienteId' => 'CLI-00017',
                'ClienteNombre' => 'Raúl Jiménez',
                'ClienteDireccion' => 'Víctor Raúl, Calle Los Pinos 123',
                'ClienteNumero' => '987654321',
                'ClienteEstado' => 'A',
                'ClienteRuc' => '11110000',
                'ClienteEliminado' => 'N',
                'ClienteUsuarioCreacion' => 'ADMIN',
                'ClienteHostCreacion' => '127.0.0.1',
                'ClienteFechaCreacion' => '2026-09-11 02:22:45.533',
                'ClienteUsuarioModificacion' => null,
                'ClienteHostModificacion' => null,
                'ClienteFechaModificacion' => null,
                'ClienteUsuarioEliminacion' => null,
                'ClienteHostEliminacion' => null,
                'ClienteFechaEliminacion' => null,
                'ClienteComprasCount' => '0',
                'ClienteTotalMonto' => '.00',
                'ClienteUltimaCompra' => null,
            ],
        ];

        // Inserción en bloques con Query Builder nativo
        foreach (array_chunk($rows, 25) as $chunk) {
            DB::table('Cliente')->insert($chunk);
        }

        // Reactivar restricciones de claves foráneas
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"');
    }
}
