<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetalleOrdenCompraSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Detalle_Orden_Compra`.
     * Total records: 26
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Detalle_Orden_Compra')->delete();

        $rows = [
            [
                'Detalle_Orden_CompraId' => '3',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00001',
                'Detalle_ProductoId' => 'PROD-00001',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '15.50',
                'Detalle_Orden_CompraSubtotal' => '155.00',
                'Detalle_Orden_CompraEliminado' => 'S',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-08 23:45:28.497',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Detalle_Orden_CompraHostEliminacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaEliminacion' => '2026-09-09 00:57:43.397',
            ],
            [
                'Detalle_Orden_CompraId' => '4',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00002',
                'Detalle_ProductoId' => 'PROD-00001',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '15.50',
                'Detalle_Orden_CompraSubtotal' => '155.00',
                'Detalle_Orden_CompraEliminado' => 'S',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-08 23:46:01.853',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Detalle_Orden_CompraHostEliminacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaEliminacion' => '2026-09-09 00:57:41.850',
            ],
            [
                'Detalle_Orden_CompraId' => '5',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00003',
                'Detalle_ProductoId' => 'PROD-00001',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '15.50',
                'Detalle_Orden_CompraSubtotal' => '155.00',
                'Detalle_Orden_CompraEliminado' => 'S',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-08 23:47:06.277',
                'Detalle_Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Detalle_Orden_CompraHostModificacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaModificacion' => '2026-09-08 23:47:06.627',
                'Detalle_Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Detalle_Orden_CompraHostEliminacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaEliminacion' => '2026-09-09 00:57:40.310',
            ],
            [
                'Detalle_Orden_CompraId' => '6',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00004',
                'Detalle_ProductoId' => 'PROD-00001',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '15.50',
                'Detalle_Orden_CompraSubtotal' => '155.00',
                'Detalle_Orden_CompraEliminado' => 'S',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-08 23:47:52.787',
                'Detalle_Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Detalle_Orden_CompraHostModificacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaModificacion' => '2026-09-08 23:47:53.007',
                'Detalle_Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Detalle_Orden_CompraHostEliminacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaEliminacion' => '2026-09-09 00:57:38.170',
            ],
            [
                'Detalle_Orden_CompraId' => '12',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00005',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '5.50',
                'Detalle_Orden_CompraSubtotal' => '55.00',
                'Detalle_Orden_CompraEliminado' => 'S',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 00:23:07.637',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Detalle_Orden_CompraHostEliminacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaEliminacion' => '2026-09-09 00:57:36.730',
            ],
            [
                'Detalle_Orden_CompraId' => '13',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00006',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00016',
                'Detalle_Orden_CompraCantidad' => '50.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '925.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 00:34:59.007',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '14',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00006',
                'Detalle_ProductoId' => 'PROD-00005',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '10.00',
                'Detalle_Orden_CompraPrecioUnitario' => '5.80',
                'Detalle_Orden_CompraSubtotal' => '58.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 00:34:59.007',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '15',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00007',
                'Detalle_ProductoId' => 'PROD-00005',
                'Detalle_UnidadMedidaId' => 'UND-00016',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '69.00',
                'Detalle_Orden_CompraSubtotal' => '345.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 00:58:16.990',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '17',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00008',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00016',
                'Detalle_Orden_CompraCantidad' => '45.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '832.50',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 01:47:08.887',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '18',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00009',
                'Detalle_ProductoId' => 'PROD-00001',
                'Detalle_UnidadMedidaId' => 'UND-00012',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '174.00',
                'Detalle_Orden_CompraSubtotal' => '870.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-09 09:52:05.340',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '19',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00010',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00015',
                'Detalle_Orden_CompraCantidad' => '20.00',
                'Detalle_Orden_CompraPrecioUnitario' => '22.00',
                'Detalle_Orden_CompraSubtotal' => '440.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:09:05.600',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '20',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00010',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00019',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '54.00',
                'Detalle_Orden_CompraSubtotal' => '270.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:09:05.600',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '21',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00011',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '20.00',
                'Detalle_Orden_CompraPrecioUnitario' => '38.00',
                'Detalle_Orden_CompraSubtotal' => '760.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:18:22.987',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '22',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00011',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '52.00',
                'Detalle_Orden_CompraSubtotal' => '260.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:18:22.987',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '23',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00011',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '92.50',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:18:22.987',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '24',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00012',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '20.00',
                'Detalle_Orden_CompraPrecioUnitario' => '38.00',
                'Detalle_Orden_CompraSubtotal' => '760.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:07.143',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '25',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00012',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '52.00',
                'Detalle_Orden_CompraSubtotal' => '260.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:07.143',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '26',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00012',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '92.50',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:07.143',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '27',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00013',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '20.00',
                'Detalle_Orden_CompraPrecioUnitario' => '38.00',
                'Detalle_Orden_CompraSubtotal' => '760.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:17.890',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '28',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00013',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '52.00',
                'Detalle_Orden_CompraSubtotal' => '260.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:17.890',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '29',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00013',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '92.50',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:17.890',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '30',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00014',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '20.00',
                'Detalle_Orden_CompraPrecioUnitario' => '38.00',
                'Detalle_Orden_CompraSubtotal' => '760.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:47.553',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '31',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00014',
                'Detalle_ProductoId' => 'PROD-00002',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '52.00',
                'Detalle_Orden_CompraSubtotal' => '260.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:47.553',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '32',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00014',
                'Detalle_ProductoId' => 'PROD-00004',
                'Detalle_UnidadMedidaId' => 'UND-00001',
                'Detalle_Orden_CompraCantidad' => '5.00',
                'Detalle_Orden_CompraPrecioUnitario' => '18.50',
                'Detalle_Orden_CompraSubtotal' => '92.50',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-10 18:19:47.553',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '33',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00015',
                'Detalle_ProductoId' => 'PROD-00003',
                'Detalle_UnidadMedidaId' => 'UND-00019',
                'Detalle_Orden_CompraCantidad' => '1.00',
                'Detalle_Orden_CompraPrecioUnitario' => '54.00',
                'Detalle_Orden_CompraSubtotal' => '54.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-11 18:12:06.127',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Detalle_Orden_CompraId' => '34',
                'Detalle_Orden_Compra_Orden_CompraId' => 'OC-00016',
                'Detalle_ProductoId' => 'PROD-00005',
                'Detalle_UnidadMedidaId' => 'UND-00016',
                'Detalle_Orden_CompraCantidad' => '2.00',
                'Detalle_Orden_CompraPrecioUnitario' => '69.00',
                'Detalle_Orden_CompraSubtotal' => '138.00',
                'Detalle_Orden_CompraEliminado' => 'N',
                'Detalle_Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Detalle_Orden_CompraHostCreacion' => '127.0.0.1',
                'Detalle_Orden_CompraFechaCreacion' => '2026-09-16 19:07:42.100',
                'Detalle_Orden_CompraUsuarioModificacion' => null,
                'Detalle_Orden_CompraHostModificacion' => null,
                'Detalle_Orden_CompraFechaModificacion' => null,
                'Detalle_Orden_CompraUsuarioEliminacion' => null,
                'Detalle_Orden_CompraHostEliminacion' => null,
                'Detalle_Orden_CompraFechaEliminacion' => null,
            ],
        ];

        // Inserción en bloques con IDENTITY_INSERT habilitado
        foreach (array_chunk($rows, 25) as $chunk) {
            if (empty($chunk)) continue;
            $columns = array_keys($chunk[0]);
            $colList = '[' . implode('], [', $columns) . ']';

            $valuesSql = [];
            foreach ($chunk as $r) {
                $valParts = [];
                foreach ($r as $val) {
                    if ($val === null) {
                        $valParts[] = 'NULL';
                    } elseif (is_numeric($val) && !is_string($val)) {
                        $valParts[] = $val;
                    } elseif (is_bool($val)) {
                        $valParts[] = $val ? '1' : '0';
                    } else {
                        $escaped = str_replace("'", "''", (string)$val);
                        $valParts[] = "N'" . $escaped . "'";
                    }
                }
                $valuesSql[] = '(' . implode(', ', $valParts) . ')';
            }

            $sql = "SET IDENTITY_INSERT [Detalle_Orden_Compra] ON;\n"
                 . "INSERT INTO [Detalle_Orden_Compra] ($colList) VALUES\n"
                 . implode(",\n", $valuesSql) . ";\n"
                 . "SET IDENTITY_INSERT [Detalle_Orden_Compra] OFF;";

            DB::unprepared($sql);
        }

        // Reactivar restricciones de claves foráneas
        // DB::statement(CHECK CONSTRAINT all);
    }
}
