<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetallePedidoProductosSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Detalle_Pedido_Productos`.
     * Total records: 49
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Detalle_Pedido_Productos')->delete();

        $rows = [
            [
                'Detalle_Pedido_ProductosId' => '1',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00001',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '15.00',
                'Detalle_Pedido_Productos_subtotal' => '30.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 03:49:49.683',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '2',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00002',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '20.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 03:49:49.727',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '3',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00003',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '10.00',
                'Detalle_Pedido_Productos_subtotal' => '10.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 03:49:49.757',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '4',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00004',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '10.00',
                'Detalle_Pedido_Productos_subtotal' => '10.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 03:49:49.787',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '5',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00005',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '15.00',
                'Detalle_Pedido_Productos_subtotal' => '15.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 09:46:10.673',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '6',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00006',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '56.00',
                'Detalle_Pedido_Productos_subtotal' => '56.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:08:17.637',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '7',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00007',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '6.50',
                'Detalle_Pedido_Productos_subtotal' => '6.50',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:26:29.547',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '8',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00008',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '6.50',
                'Detalle_Pedido_Productos_subtotal' => '6.50',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:33:28.897',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '9',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00009',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '71.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:51:20.467',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '10',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00010',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '71.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:51:44.797',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '11',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00011',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '71.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 10:51:58.633',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '12',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00012',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '70.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '.00',
                'Detalle_Pedido_Productos_subtotal' => '.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 14:24:26.537',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '50.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '20.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '14',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00013',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '10.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '1760.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 14:37:26.073',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '10.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '15',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00014',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '4.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '6.50',
                'Detalle_Pedido_Productos_subtotal' => '26.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 14:56:07.120',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '3.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '1.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => null,
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '16',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00015',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '10.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '710.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 16:30:42.000',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '120.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '12.00',
                'Detalle_Pedido_Productos_cantidad_base' => '120.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '17',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00016',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '142.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 16:44:58.807',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '24.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '12.00',
                'Detalle_Pedido_Productos_cantidad_base' => '24.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '18',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00017',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '20.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '400.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-09 16:50:06.673',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '300.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '15.00',
                'Detalle_Pedido_Productos_cantidad_base' => '300.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '19',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00018',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '10.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '710.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 15:46:33.577',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '120.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '12.00',
                'Detalle_Pedido_Productos_cantidad_base' => '120.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '20',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00019',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '10.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '200.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 15:53:27.610',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '150.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00017',
                'Detalle_Pedido_Productos_factor_conversion' => '15.00',
                'Detalle_Pedido_Productos_cantidad_base' => '150.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '21',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00011',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '4.00',
                'Detalle_Pedido_Productos_subtotal' => '8.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 16:50:32.207',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '2.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00006',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '2.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '22',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00020',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '66.08',
                'Detalle_Pedido_Productos_subtotal' => '66.08',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 17:02:31.307',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '24.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '24.00',
                'Detalle_Pedido_Productos_cantidad_base' => '24.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '23',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00021',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '56.00',
                'Detalle_Pedido_Productos_subtotal' => '56.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 17:17:40.287',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '24.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00019',
                'Detalle_Pedido_Productos_factor_conversion' => '24.00',
                'Detalle_Pedido_Productos_cantidad_base' => '24.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '24',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00022',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '45.00',
                'Detalle_Pedido_Productos_subtotal' => '90.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:18:23.247',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '2.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '2.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '25',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00022',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '60.00',
                'Detalle_Pedido_Productos_subtotal' => '60.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:18:23.253',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '26',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00022',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00004',
                'Detalle_Pedido_Productos_cantidad' => '3.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '22.00',
                'Detalle_Pedido_Productos_subtotal' => '66.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:18:23.257',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '3.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '3.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '27',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00023',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '45.00',
                'Detalle_Pedido_Productos_subtotal' => '90.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:19:17.930',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '2.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '2.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '28',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00023',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '60.00',
                'Detalle_Pedido_Productos_subtotal' => '60.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:19:17.937',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '29',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00023',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00004',
                'Detalle_Pedido_Productos_cantidad' => '3.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '22.00',
                'Detalle_Pedido_Productos_subtotal' => '66.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 18:19:17.940',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '3.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '3.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '30',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00024',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00004',
                'Detalle_Pedido_Productos_cantidad' => '6.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '26.00',
                'Detalle_Pedido_Productos_subtotal' => '156.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 19:14:59.737',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '14.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '22.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00015',
                'Detalle_Pedido_Productos_factor_conversion' => '6.00',
                'Detalle_Pedido_Productos_cantidad_base' => '36.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '31',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00024',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00006',
                'Detalle_Pedido_Productos_cantidad' => '3.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '22.00',
                'Detalle_Pedido_Productos_subtotal' => '66.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-10 19:14:59.743',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '18.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '6.00',
                'Detalle_Pedido_Productos_cantidad_base' => '18.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '32',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00025',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00004',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '26.00',
                'Detalle_Pedido_Productos_subtotal' => '52.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 03:01:41.643',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '12.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00015',
                'Detalle_Pedido_Productos_factor_conversion' => '6.00',
                'Detalle_Pedido_Productos_cantidad_base' => '12.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '33',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00026',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '40.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 13:23:16.963',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '30.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00017',
                'Detalle_Pedido_Productos_factor_conversion' => '15.00',
                'Detalle_Pedido_Productos_cantidad_base' => '30.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '34',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00026',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '2.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '2.50',
                'Detalle_Pedido_Productos_subtotal' => '5.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 13:23:16.967',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '12.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'pack',
                'Detalle_Pedido_Productos_factor_conversion' => '6.00',
                'Detalle_Pedido_Productos_cantidad_base' => '12.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '35',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00027',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '2.00',
                'Detalle_Pedido_Productos_subtotal' => '2.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 17:35:17.860',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '36',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00028',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '20.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 17:35:17.893',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '15.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00017',
                'Detalle_Pedido_Productos_factor_conversion' => '15.00',
                'Detalle_Pedido_Productos_cantidad_base' => '15.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '37',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00029',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '2.00',
                'Detalle_Pedido_Productos_subtotal' => '2.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 17:46:05.673',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '39',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00030',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00003',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '56.00',
                'Detalle_Pedido_Productos_subtotal' => '56.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-11 18:11:00.910',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '24.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00019',
                'Detalle_Pedido_Productos_factor_conversion' => '24.00',
                'Detalle_Pedido_Productos_cantidad_base' => '24.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '41',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00031',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 18:58:16.077',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '42',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00032',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:06:06.893',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '43',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00033',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:06:59.500',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '44',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00034',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:12:35.597',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '45',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00035',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:12:35.707',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '50.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00012',
                'Detalle_Pedido_Productos_factor_conversion' => '50.00',
                'Detalle_Pedido_Productos_cantidad_base' => '50.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '46',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00036',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:16:12.430',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '50.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00012',
                'Detalle_Pedido_Productos_factor_conversion' => '50.00',
                'Detalle_Pedido_Productos_cantidad_base' => '50.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '47',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00037',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:16:12.580',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '48',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00038',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:17:47.970',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '50.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00012',
                'Detalle_Pedido_Productos_factor_conversion' => '50.00',
                'Detalle_Pedido_Productos_cantidad_base' => '50.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '49',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00039',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00001',
                'Detalle_Pedido_Productos_cantidad' => '1.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '176.00',
                'Detalle_Pedido_Productos_subtotal' => '176.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:17:48.147',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '1.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00001',
                'Detalle_Pedido_Productos_factor_conversion' => '1.00',
                'Detalle_Pedido_Productos_cantidad_base' => '1.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '50',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00040',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00005',
                'Detalle_Pedido_Productos_cantidad' => '3.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '71.00',
                'Detalle_Pedido_Productos_subtotal' => '213.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:20:24.160',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '36.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00016',
                'Detalle_Pedido_Productos_factor_conversion' => '12.00',
                'Detalle_Pedido_Productos_cantidad_base' => '36.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '51',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00040',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00004',
                'Detalle_Pedido_Productos_cantidad' => '10.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '26.00',
                'Detalle_Pedido_Productos_subtotal' => '260.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:20:24.167',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '60.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00015',
                'Detalle_Pedido_Productos_factor_conversion' => '6.00',
                'Detalle_Pedido_Productos_cantidad_base' => '60.00',
            ],
            [
                'Detalle_Pedido_ProductosId' => '52',
                'Detalle_Pedido_Productos_PedidoId' => 'PED-00041',
                'Detalle_Pedido_Productos_ProductoId' => 'PROD-00002',
                'Detalle_Pedido_Productos_cantidad' => '3.00',
                'Detalle_Pedido_Productos_precio_unitario_venta' => '20.00',
                'Detalle_Pedido_Productos_subtotal' => '60.00',
                'Detalle_Pedido_ProductosEliminado' => 'N',
                'Detalle_Pedido_ProductosUsuarioCreacion' => 'ADMIN',
                'Detalle_Pedido_ProductosHostCreacion' => '127.0.0.1',
                'Detalle_Pedido_ProductosFechaCreacion' => '2026-09-26 19:41:32.757',
                'Detalle_Pedido_ProductosUsuarioModificacion' => null,
                'Detalle_Pedido_ProductosHostModificacion' => null,
                'Detalle_Pedido_ProductosFechaModificacion' => null,
                'Detalle_Pedido_ProductosUsuarioEliminacion' => null,
                'Detalle_Pedido_ProductosHostEliminacion' => null,
                'Detalle_Pedido_ProductosFechaEliminacion' => null,
                'Detalle_Pedido_Productos_cantidad_fisica' => '45.00',
                'Detalle_Pedido_Productos_cantidad_virtual' => '.00',
                'Detalle_Pedido_Productos_unidades_medidaId' => 'UND-00017',
                'Detalle_Pedido_Productos_factor_conversion' => '15.00',
                'Detalle_Pedido_Productos_cantidad_base' => '45.00',
            ],
        ];

        // Inserción en bloques con IDENTITY_INSERT habilitado
        foreach (array_chunk($rows, 25) as $chunk) {
            if (empty($chunk)) continue;
            $columns = array_keys($chunk[0]);
            $colList = '[' . implode('], [', $columns) . ']';

            $valuesSql = [];
            foreach ($chunk as $r) {
                $valParts = [];
                foreach ($r as $val) {
                    if ($val === null) {
                        $valParts[] = 'NULL';
                    } elseif (is_numeric($val) && !is_string($val)) {
                        $valParts[] = $val;
                    } elseif (is_bool($val)) {
                        $valParts[] = $val ? '1' : '0';
                    } else {
                        $escaped = str_replace("'", "''", (string)$val);
                        $valParts[] = "N'" . $escaped . "'";
                    }
                }
                $valuesSql[] = '(' . implode(', ', $valParts) . ')';
            }

            $sql = "SET IDENTITY_INSERT [Detalle_Pedido_Productos] ON;\n"
                 . "INSERT INTO [Detalle_Pedido_Productos] ($colList) VALUES\n"
                 . implode(",\n", $valuesSql) . ";\n"
                 . "SET IDENTITY_INSERT [Detalle_Pedido_Productos] OFF;";

            DB::unprepared($sql);
        }

        // Reactivar restricciones de claves foráneas
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"');
    }
}
