<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetalleProductoMedidaSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Detalle_Producto_medida`.
     * Total records: 25
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Detalle_Producto_medida')->delete();

        $rows = [
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '4.00',
                'Detalle_Producto_medida_precio_compra' => '3.80',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-04 21:28:59.820',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 22:52:01.980',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00003',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '176.00',
                'Detalle_Producto_medida_precio_compra' => '174.00',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 22:37:59.737',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 22:52:01.980',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00004',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '4.00',
                'Detalle_Producto_medida_precio_compra' => '3.80',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-04 21:28:59.820',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 22:52:01.980',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00005',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '176.00',
                'Detalle_Producto_medida_precio_compra' => '174.00',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 22:32:23.813',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 22:52:01.980',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00006',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '4.00',
                'Detalle_Producto_medida_precio_compra' => '3.80',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-04 23:15:17.010',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00012',
                'Detalle_Producto_medida_factor_conversion' => '50',
                'Detalle_Producto_medida_precio_venta' => '176.00',
                'Detalle_Producto_medida_precio_compra' => '174.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 22:42:13.257',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00013',
                'Detalle_Producto_medida_factor_conversion' => '25',
                'Detalle_Producto_medida_precio_venta' => '88.00',
                'Detalle_Producto_medida_precio_compra' => '86.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:01:09.593',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00001',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00014',
                'Detalle_Producto_medida_factor_conversion' => '10',
                'Detalle_Producto_medida_precio_venta' => '40.00',
                'Detalle_Producto_medida_precio_compra' => '36.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:01:09.593',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-09 01:15:02.910',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00002',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '2.00',
                'Detalle_Producto_medida_precio_compra' => '1.80',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-04 23:16:30.180',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-10 15:52:35.017',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00002',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00005',
                'Detalle_Producto_medida_factor_conversion' => '15',
                'Detalle_Producto_medida_precio_venta' => '20.00',
                'Detalle_Producto_medida_precio_compra' => '18.50',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 20:40:39.427',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-07 23:04:03.660',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 23:04:03.660',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00002',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00016',
                'Detalle_Producto_medida_factor_conversion' => '15',
                'Detalle_Producto_medida_precio_venta' => '20.00',
                'Detalle_Producto_medida_precio_compra' => '18.50',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:04:03.660',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-10 15:52:35.017',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00002',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00017',
                'Detalle_Producto_medida_factor_conversion' => '15',
                'Detalle_Producto_medida_precio_venta' => '20.00',
                'Detalle_Producto_medida_precio_compra' => '18.50',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 15:52:35.017',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00003',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '2.50',
                'Detalle_Producto_medida_precio_compra' => '1.80',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 19:19:07.177',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-10 16:58:54.583',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00003',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00002',
                'Detalle_Producto_medida_factor_conversion' => '12',
                'Detalle_Producto_medida_precio_venta' => '28.00',
                'Detalle_Producto_medida_precio_compra' => '26.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 21:05:13.957',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-10 16:58:54.583',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00003',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00005',
                'Detalle_Producto_medida_factor_conversion' => '24',
                'Detalle_Producto_medida_precio_venta' => '56.00',
                'Detalle_Producto_medida_precio_compra' => '54.00',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 21:05:13.957',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-05 21:51:35.163',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-10 16:58:54.583',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00003',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00019',
                'Detalle_Producto_medida_factor_conversion' => '24',
                'Detalle_Producto_medida_precio_venta' => '56.00',
                'Detalle_Producto_medida_precio_compra' => '54.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 16:58:54.583',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00004',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '7.00',
                'Detalle_Producto_medida_precio_compra' => '6.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 20:55:19.200',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-07 23:03:43.870',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00004',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00005',
                'Detalle_Producto_medida_factor_conversion' => '7',
                'Detalle_Producto_medida_precio_venta' => '7.00',
                'Detalle_Producto_medida_precio_compra' => '6.00',
                'Detalle_Producto_medidaEliminado' => 'S',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-05 20:55:19.200',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-07 23:03:43.870',
                'Detalle_Producto_medidaUsuarioEliminacion' => 'ADMIN',
                'Detalle_Producto_medidaHostEliminacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaEliminacion' => '2026-09-07 23:03:43.870',
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00004',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00015',
                'Detalle_Producto_medida_factor_conversion' => '6',
                'Detalle_Producto_medida_precio_venta' => '26.00',
                'Detalle_Producto_medida_precio_compra' => '22.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:03:43.870',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00005',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '6.50',
                'Detalle_Producto_medida_precio_compra' => '5.80',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:09:35.200',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-23 22:15:05.697',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00005',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00016',
                'Detalle_Producto_medida_factor_conversion' => '12',
                'Detalle_Producto_medida_precio_venta' => '71.00',
                'Detalle_Producto_medida_precio_compra' => '69.00',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-07 23:09:35.200',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-23 22:15:05.697',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00006',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '2.00',
                'Detalle_Producto_medida_precio_compra' => '1.80',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 18:25:54.140',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00006',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00017',
                'Detalle_Producto_medida_factor_conversion' => '15',
                'Detalle_Producto_medida_precio_venta' => '22.00',
                'Detalle_Producto_medida_precio_compra' => '20.50',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 18:25:54.140',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00007',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00001',
                'Detalle_Producto_medida_factor_conversion' => '1',
                'Detalle_Producto_medida_precio_venta' => '4.50',
                'Detalle_Producto_medida_precio_compra' => '3.20',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 18:27:47.063',
                'Detalle_Producto_medidaUsuarioModificacion' => 'ADMIN',
                'Detalle_Producto_medidaHostModificacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaModificacion' => '2026-09-10 18:28:32.543',
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
            [
                'Detalle_Producto_medida_ProductoId' => 'PROD-00007',
                'Detalle_Producto_medida_unidades_medidaId' => 'UND-00024',
                'Detalle_Producto_medida_factor_conversion' => '6',
                'Detalle_Producto_medida_precio_venta' => '19.00',
                'Detalle_Producto_medida_precio_compra' => '17.50',
                'Detalle_Producto_medidaEliminado' => 'N',
                'Detalle_Producto_medidaUsuarioCreacion' => 'ADMIN',
                'Detalle_Producto_medidaHostCreacion' => '127.0.0.1',
                'Detalle_Producto_medidaFechaCreacion' => '2026-09-10 18:28:32.543',
                'Detalle_Producto_medidaUsuarioModificacion' => null,
                'Detalle_Producto_medidaHostModificacion' => null,
                'Detalle_Producto_medidaFechaModificacion' => null,
                'Detalle_Producto_medidaUsuarioEliminacion' => null,
                'Detalle_Producto_medidaHostEliminacion' => null,
                'Detalle_Producto_medidaFechaEliminacion' => null,
            ],
        ];

        // Inserción en bloques con Query Builder nativo
        foreach (array_chunk($rows, 25) as $chunk) {
            DB::table('Detalle_Producto_medida')->insert($chunk);
        }

        // Reactivar restricciones de claves foráneas
        // DB::statement(CHECK CONSTRAINT all);
    }
}
