<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrdenCompraSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Orden_Compra`.
     * Total records: 16
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Orden_Compra')->delete();

        $rows = [
            [
                'Orden_CompraId' => 'OC-00001',
                'Orden_CompraFecha' => '2026-09-08 23:45:28.480',
                'Orden_CompraSubtotal' => '155.00',
                'Orden_CompraIgv' => '27.90',
                'Orden_CompraTotal' => '182.90',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Orden de prueba automatizada para verificación de flujo',
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'S',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-08 23:45:28.497',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Orden_CompraHostEliminacion' => '127.0.0.1',
                'Orden_CompraFechaEliminacion' => '2026-09-09 00:57:43.400',
            ],
            [
                'Orden_CompraId' => 'OC-00002',
                'Orden_CompraFecha' => '2026-09-08 23:46:01.843',
                'Orden_CompraSubtotal' => '155.00',
                'Orden_CompraIgv' => '27.90',
                'Orden_CompraTotal' => '182.90',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Test de creacion',
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'S',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-08 23:46:01.847',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Orden_CompraHostEliminacion' => '127.0.0.1',
                'Orden_CompraFechaEliminacion' => '2026-09-09 00:57:41.853',
            ],
            [
                'Orden_CompraId' => 'OC-00003',
                'Orden_CompraFecha' => '2026-09-08 23:47:06.270',
                'Orden_CompraSubtotal' => '155.00',
                'Orden_CompraIgv' => '27.90',
                'Orden_CompraTotal' => '182.90',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Orden de prueba automatizada para verificación de flujo',
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'S',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-08 23:47:06.277',
                'Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Orden_CompraHostModificacion' => '127.0.0.1',
                'Orden_CompraFechaModificacion' => '2026-09-08 23:47:06.630',
                'Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Orden_CompraHostEliminacion' => '127.0.0.1',
                'Orden_CompraFechaEliminacion' => '2026-09-09 00:57:40.310',
            ],
            [
                'Orden_CompraId' => 'OC-00004',
                'Orden_CompraFecha' => '2026-09-08 23:47:52.780',
                'Orden_CompraSubtotal' => '155.00',
                'Orden_CompraIgv' => '27.90',
                'Orden_CompraTotal' => '182.90',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Orden de prueba automatizada para verificación de flujo',
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'S',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-08 23:47:52.787',
                'Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Orden_CompraHostModificacion' => '127.0.0.1',
                'Orden_CompraFechaModificacion' => '2026-09-08 23:47:53.010',
                'Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Orden_CompraHostEliminacion' => '127.0.0.1',
                'Orden_CompraFechaEliminacion' => '2026-09-09 00:57:38.173',
            ],
            [
                'Orden_CompraId' => 'OC-00005',
                'Orden_CompraFecha' => '2026-09-09 00:23:07.627',
                'Orden_CompraSubtotal' => '55.00',
                'Orden_CompraIgv' => '9.90',
                'Orden_CompraTotal' => '64.90',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Test de integración módulo front-back',
                'Orden_Compra_ProveedorId' => 'PRV-00004',
                'Orden_CompraEliminado' => 'S',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-09 00:23:07.633',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => 'ADMIN',
                'Orden_CompraHostEliminacion' => '127.0.0.1',
                'Orden_CompraFechaEliminacion' => '2026-09-09 00:57:36.737',
            ],
            [
                'Orden_CompraId' => 'OC-00006',
                'Orden_CompraFecha' => '2026-09-09 00:34:59.000',
                'Orden_CompraSubtotal' => '983.00',
                'Orden_CompraIgv' => '176.94',
                'Orden_CompraTotal' => '1159.94',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-09 00:34:59.003',
                'Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Orden_CompraHostModificacion' => '127.0.0.1',
                'Orden_CompraFechaModificacion' => '2026-09-09 00:34:59.067',
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00007',
                'Orden_CompraFecha' => '2026-09-09 00:58:16.987',
                'Orden_CompraSubtotal' => '345.00',
                'Orden_CompraIgv' => '62.10',
                'Orden_CompraTotal' => '407.10',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-09 00:58:16.987',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00008',
                'Orden_CompraFecha' => '2026-09-09 01:47:08.883',
                'Orden_CompraSubtotal' => '832.50',
                'Orden_CompraIgv' => '149.85',
                'Orden_CompraTotal' => '982.35',
                'Orden_CompraEstado' => 'A',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-09 01:47:08.887',
                'Orden_CompraUsuarioModificacion' => 'ADMIN',
                'Orden_CompraHostModificacion' => '127.0.0.1',
                'Orden_CompraFechaModificacion' => '2026-09-09 02:57:47.493',
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00009',
                'Orden_CompraFecha' => '2026-09-09 09:52:05.320',
                'Orden_CompraSubtotal' => '870.00',
                'Orden_CompraIgv' => '156.60',
                'Orden_CompraTotal' => '1026.60',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-09 09:52:05.337',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00010',
                'Orden_CompraFecha' => '2026-09-10 18:09:05.593',
                'Orden_CompraSubtotal' => '710.00',
                'Orden_CompraIgv' => '127.80',
                'Orden_CompraTotal' => '837.80',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-10 18:09:05.597',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00011',
                'Orden_CompraFecha' => '2026-09-10 18:18:22.647',
                'Orden_CompraSubtotal' => '1112.50',
                'Orden_CompraIgv' => '200.25',
                'Orden_CompraTotal' => '1312.75',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-10 18:18:22.983',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00012',
                'Orden_CompraFecha' => '2026-09-10 18:19:07.133',
                'Orden_CompraSubtotal' => '1112.50',
                'Orden_CompraIgv' => '200.25',
                'Orden_CompraTotal' => '1312.75',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-10 18:19:07.140',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00013',
                'Orden_CompraFecha' => '2026-09-10 18:19:17.883',
                'Orden_CompraSubtotal' => '1112.50',
                'Orden_CompraIgv' => '200.25',
                'Orden_CompraTotal' => '1312.75',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00001',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-10 18:19:17.887',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00014',
                'Orden_CompraFecha' => '2026-09-10 18:19:47.543',
                'Orden_CompraSubtotal' => '1112.50',
                'Orden_CompraIgv' => '200.25',
                'Orden_CompraTotal' => '1312.75',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00005',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-10 18:19:47.550',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00015',
                'Orden_CompraFecha' => '2026-09-11 18:12:06.117',
                'Orden_CompraSubtotal' => '54.00',
                'Orden_CompraIgv' => '9.72',
                'Orden_CompraTotal' => '63.72',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => 'Reposición de salida/pedido para Bodega Los Amigos: Bonlé x 24 unidades.',
                'Orden_Compra_ProveedorId' => 'PRV-00004',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-11 18:12:06.123',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
            [
                'Orden_CompraId' => 'OC-00016',
                'Orden_CompraFecha' => '2026-09-16 19:07:42.093',
                'Orden_CompraSubtotal' => '138.00',
                'Orden_CompraIgv' => '24.84',
                'Orden_CompraTotal' => '162.84',
                'Orden_CompraEstado' => 'P',
                'Orden_CompraObservacion' => null,
                'Orden_Compra_ProveedorId' => 'PRV-00006',
                'Orden_CompraEliminado' => 'N',
                'Orden_CompraUsuarioCreacion' => 'ADMIN',
                'Orden_CompraHostCreacion' => '127.0.0.1',
                'Orden_CompraFechaCreacion' => '2026-09-16 19:07:42.097',
                'Orden_CompraUsuarioModificacion' => null,
                'Orden_CompraHostModificacion' => null,
                'Orden_CompraFechaModificacion' => null,
                'Orden_CompraUsuarioEliminacion' => null,
                'Orden_CompraHostEliminacion' => null,
                'Orden_CompraFechaEliminacion' => null,
            ],
        ];

        // Inserción en bloques con Query Builder nativo
        foreach (array_chunk($rows, 25) as $chunk) {
            DB::table('Orden_Compra')->insert($chunk);
        }

        // Reactivar restricciones de claves foráneas
        // DB::statement(CHECK CONSTRAINT all);
    }
}
