<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Auto-generated from database table `Producto`.
     * Total records: 7
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('Producto')->delete();

        $rows = [
            [
                'ProductoId' => 'PROD-00001',
                'ProductoNombre' => 'Arroz Delite',
                'Producto_Categoria_ProductoId' => 'CAT-00002',
                'ProductoMarca' => 'Deleite',
                'ProductoStockActual' => '369',
                'ProductoStockMinimo' => '20',
                'ProductoStockMaximo' => '50',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-04 21:28:59.810',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-26 19:17:47.530',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'Arroz extra costeño grano largo seleccionado',
                'producto_imagen' => 'U0iyO6prNQJP8ev09hoh7UQzXX5i5zXbmn2VkE5T.jpg',
                'Producto_producto_ubi_id' => 'UBI-00001',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona A - Bebidas',
                'ProductoUbicacion' => 'Pasillo 1 - Estante A',
            ],
            [
                'ProductoId' => 'PROD-00002',
                'ProductoNombre' => 'Guarana  500ml',
                'Producto_Categoria_ProductoId' => 'CAT-00003',
                'ProductoMarca' => 'Guarana',
                'ProductoStockActual' => '95',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '150',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-04 23:16:30.180',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-10 15:52:35.013',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'No se ingresó descripción',
                'producto_imagen' => 'Sin imagenes,',
                'Producto_producto_ubi_id' => 'UBI-00001',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona A - Bebidas',
                'ProductoUbicacion' => 'Pasillo 1 - Estante B',
            ],
            [
                'ProductoId' => 'PROD-00003',
                'ProductoNombre' => 'Bonle 400 ml',
                'Producto_Categoria_ProductoId' => 'CAT-00001',
                'ProductoMarca' => 'Bonle',
                'ProductoStockActual' => '11',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '100',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-05 19:19:07.173',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-10 16:58:54.580',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'leche en lata',
                'producto_imagen' => '/storage/productos/KatcFKGuqkUnfGc5V6LMpO9qvqeMkEhtrHcj3dWD.jpg',
                'Producto_producto_ubi_id' => 'UBI-00002',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona B - Abarrotes',
                'ProductoUbicacion' => 'Pasillo 2 - Estante A',
            ],
            [
                'ProductoId' => 'PROD-00004',
                'ProductoNombre' => 'Pepsi 2 litros',
                'Producto_Categoria_ProductoId' => 'CAT-00003',
                'ProductoMarca' => 'Pepsi',
                'ProductoStockActual' => '161',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '150',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-05 20:55:19.197',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-11 03:52:41.127',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'No se ingresó descripción',
                'producto_imagen' => '/storage/productos/XcPtokBjJKQM21QJ8qMaNrg0CPLYYhci0sSJxflL.jpg',
                'Producto_producto_ubi_id' => 'UBI-00002',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona A - Bebidas',
                'ProductoUbicacion' => 'Pasillo 1 - Estante C',
            ],
            [
                'ProductoId' => 'PROD-00005',
                'ProductoNombre' => 'Aceite Chef 900ml',
                'Producto_Categoria_ProductoId' => 'CAT-00008',
                'ProductoMarca' => 'Chef',
                'ProductoStockActual' => '84',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '50',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-07 23:09:35.197',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-23 22:15:05.690',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'Aciete',
                'producto_imagen' => 'Sin imagenes,',
                'Producto_producto_ubi_id' => 'UBI-00002',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona B - Abarrotes',
                'ProductoUbicacion' => 'Pasillo 2 - Estante B',
            ],
            [
                'ProductoId' => 'PROD-00006',
                'ProductoNombre' => 'Pepsi 500ml',
                'Producto_Categoria_ProductoId' => 'CAT-00003',
                'ProductoMarca' => 'Pepsi',
                'ProductoStockActual' => '12',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '1000',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-10 18:25:54.137',
                'ProductoUsuarioModificacion' => null,
                'ProductoHostModificacion' => null,
                'ProductoFechaModificacion' => null,
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'Bebida',
                'producto_imagen' => 'Sin imagenes,',
                'Producto_producto_ubi_id' => 'UBI-00002',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona C - Lácteos',
                'ProductoUbicacion' => 'Pasillo 3 - Estante A',
            ],
            [
                'ProductoId' => 'PROD-00007',
                'ProductoNombre' => 'Pepsi 1.500 L',
                'Producto_Categoria_ProductoId' => 'CAT-00003',
                'ProductoMarca' => 'Pepsi',
                'ProductoStockActual' => '240',
                'ProductoStockMinimo' => '5',
                'ProductoStockMaximo' => '1000',
                'ProductoEstado' => 'A',
                'ProductoEliminado' => 'N',
                'ProductoUsuarioCreacion' => 'ADMIN',
                'ProductoHostCreacion' => '127.0.0.1',
                'ProductoFechaCreacion' => '2026-09-10 18:27:47.060',
                'ProductoUsuarioModificacion' => 'ADMIN',
                'ProductoHostModificacion' => '127.0.0.1',
                'ProductoFechaModificacion' => '2026-09-10 18:29:35.110',
                'ProductoUsuarioEliminacion' => null,
                'ProductoHostEliminacion' => null,
                'ProductoFechaEliminacion' => null,
                'producto_descripcion' => 'Bebida',
                'producto_imagen' => 'Sin imagenes,',
                'Producto_producto_ubi_id' => 'UBI-00002',
                'ProductoStockVirtual' => '50.00',
                'ProductoStockVirtualConsumido' => '.00',
                'ProductoZona' => 'Zona C - Lácteos',
                'ProductoUbicacion' => 'Pasillo 3 - Estante B',
            ],
        ];

        // Inserción en bloques con Query Builder nativo
        foreach (array_chunk($rows, 25) as $chunk) {
            DB::table('Producto')->insert($chunk);
        }

        // Reactivar restricciones de claves foráneas
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"');
    }
}
