<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnidadesMedidaSeeder extends Seeder
{
    /**
     * Auto-generated from database table `unidades_medida`.
     * Total records: 26
     */
    public function run(): void
    {
        // Desactivar restricciones de claves foráneas temporalmente
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"');

        // Limpiar tabla antes de poblar
        DB::table('unidades_medida')->delete();

        $rows = [
            [
                'unidades_medidaId' => 'UND-00001',
                'unidades_medidaDescripcionUnidades' => 'Unidad (UND)',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'UND',
                'unidades_medidaEsBase' => '1',
            ],
            [
                'unidades_medidaId' => 'UND-00002',
                'unidades_medidaDescripcionUnidades' => 'DOCENA*12 UND',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 17:04:02.460',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'DOC12',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00003',
                'unidades_medidaDescripcionUnidades' => 'Caja x 24 UND',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => null,
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00004',
                'unidades_medidaDescripcionUnidades' => 'Caja x 48 UND',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => null,
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00005',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE*4',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 17:07:16.667',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PAQ4',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00006',
                'unidades_medidaDescripcionUnidades' => 'Kilogramo (KG)',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-07 22:35:24.387',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'KG',
                'unidades_medidaEsBase' => '1',
            ],
            [
                'unidades_medidaId' => 'UND-00007',
                'unidades_medidaDescripcionUnidades' => 'Litro (LT)',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'SYSTEM',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-08-24 10:34:15.987',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-07 22:39:29.913',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'lt',
                'unidades_medidaEsBase' => '1',
            ],
            [
                'unidades_medidaId' => 'UND-00008',
                'unidades_medidaDescripcionUnidades' => 'MEDIA/DOCENA *6',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-05 19:19:07.170',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 17:04:39.337',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'MEDOC6',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00009',
                'unidades_medidaDescripcionUnidades' => 'MEDIA DOCENA * 6',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:34:30.317',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-07 22:35:09.203',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => '1/4',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00010',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:35:02.580',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-07 23:02:29.027',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'Paq',
                'unidades_medidaEsBase' => '1',
            ],
            [
                'unidades_medidaId' => 'UND-00011',
                'unidades_medidaDescripcionUnidades' => 'Unidad',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:35:37.277',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'Uno',
                'unidades_medidaEsBase' => '1',
            ],
            [
                'unidades_medidaId' => 'UND-00012',
                'unidades_medidaDescripcionUnidades' => 'BOLSA x 50',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:40:09.050',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'BOLSA',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00013',
                'unidades_medidaDescripcionUnidades' => 'BOLSA*25',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:59:02.653',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 17:01:24.473',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'bOL*25',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00014',
                'unidades_medidaDescripcionUnidades' => 'BOLSA*10',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 22:59:50.967',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 17:01:20.123',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'Bol10',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00015',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE *6',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 23:02:15.020',
                'unidades_medidaUsuarioModificacion' => 'ADMIN',
                'unidades_medidaHostModificacion' => '127.0.0.1',
                'unidades_medidaFechaModificacion' => '2026-09-09 16:57:21.390',
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PAQ6',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00016',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE*12',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 23:02:43.750',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PAQT12',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00017',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE*15',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 23:02:56.367',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PAQT15',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00018',
                'unidades_medidaDescripcionUnidades' => 'PAQUETE*20',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-07 23:03:10.267',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PAQ20',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00019',
                'unidades_medidaDescripcionUnidades' => 'CAJA*24',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 16:56:59.760',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'CAJ24',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00020',
                'unidades_medidaDescripcionUnidades' => 'CAJA*48',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 16:58:02.070',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'CAJ48',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00021',
                'unidades_medidaDescripcionUnidades' => 'CAJA*74',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 16:58:10.967',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'CAJ74',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00022',
                'unidades_medidaDescripcionUnidades' => 'DISPALY*6',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 16:59:08.517',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'DISP6',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00023',
                'unidades_medidaDescripcionUnidades' => 'DISPLAY*8',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 16:59:48.063',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'DISP8',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00024',
                'unidades_medidaDescripcionUnidades' => 'PACK*6',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 17:02:34.543',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PACK6',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00025',
                'unidades_medidaDescripcionUnidades' => 'PACK*8',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 17:02:44.527',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PACK8',
                'unidades_medidaEsBase' => '0',
            ],
            [
                'unidades_medidaId' => 'UND-00026',
                'unidades_medidaDescripcionUnidades' => 'PACK*4',
                'unidades_medidaEstadoUnidades' => 'A',
                'unidades_medidaEliminado' => 'N',
                'unidades_medidaUsuarioCreacion' => 'ADMIN',
                'unidades_medidaHostCreacion' => '127.0.0.1',
                'unidades_medidaFechaCreacion' => '2026-09-09 17:02:53.993',
                'unidades_medidaUsuarioModificacion' => null,
                'unidades_medidaHostModificacion' => null,
                'unidades_medidaFechaModificacion' => null,
                'unidades_medidaUsuarioEliminacion' => null,
                'unidades_medidaHostEliminacion' => null,
                'unidades_medidaFechaEliminacion' => null,
                'unidades_medidaAbreviatura' => 'PACK4',
                'unidades_medidaEsBase' => '0',
            ],
        ];

        // Inserción en bloques con Query Builder nativo
        foreach (array_chunk($rows, 25) as $chunk) {
            DB::table('unidades_medida')->insert($chunk);
        }

        // Reactivar restricciones de claves foráneas
        DB::statement('EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"');
    }
}
